[package]
name = "gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.23.0"
eframe = "0.14.0"
log = "0.4"
serde = { version = "1.0.136", features = ["derive"] }
api= { path = "../api/" }
