[package]
name = "gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
api= { path = "../api/" }
egui = "0.23.0"
eframe = "0.23.0"
log = "0.4"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1.4.1", features = ["v4", "fast-rng"] }
